site_name: PCF Tile Developers Guide
copyright: Copyright (C) 2016 Pivotal Software Inc.
theme: mkdocs
theme_dir: theme

pages:
- 'Home': 'index.md'
- 'Developer Guide':
  - 'Getting Started': 'getting-started.md'
  - 'Cloud Foundry Concepts': 'cf-concepts.md'
  - 'Stages of Integration': 'stages.md'
  - 'Development Process': 'development.md'
  - 'Documentation': 'tile-documentation.md'
  - 'Continuous Integration': 'concourse.md'
- 'Reference':
  - 'Commands':
    - 'Tile Generator': 'tile-generator.md'
    - 'PCF Command': 'pcf-command.md'
    - 'Concourse': 'concourse.md'
  - 'Components':
    - 'Service Brokers': 'service-brokers.md'
    - 'Managed Services': 'managed-services.md'
    - 'Dynamic Services': 'dynamic-services.md'
    - 'Buildpacks': 'buildpacks.md'
    - 'Embedded Agents': 'embedded-agents.md'
    - 'Nozzles': 'nozzles.md'
  - 'Setup':
    - 'Developer Environment': 'setup-pcfdev.md'
    - 'Full PCF Environment': 'setup-pcf.md'
  - 'Troubleshooting': 'troubleshooting.md'
- 'Contacts': 'contacts.md'

markdown_extensions:
  - toc:
      permalink:
  - admonition:
