---

resources:

- name: documentation-repo
  type: git
  source:
    paths: [ "mkdocs.yml", "docs" ]
    branch: master
    uri: http://github.com/cf-platform-eng/isv-portal.git

- name: github-pages
  type: git
  source:
    branch: gh-pages
    uri: git@github.com:cf-platform-eng/isv-portal.git
    private_key: {{github-pages-private-key}}

- name: dockerfile-repo
  type: git
  source:
    paths: [ "ci/Dockerfile" ]
    branch: master
    uri: http://github.com/cf-platform-eng/isv-portal.git

- name: ci-docker-image
  type: docker-image
  source:
    repository: guidowb/mkdocs-pipeline
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:

- name: build-docker
  plan:
  - get: dockerfile-repo
    trigger: true
  - put: ci-docker-image
    params:
      build: dockerfile-repo/ci

- name: update-docs
  plan:
  - aggregate:
    - get: ci-docker-image
      passed: [ build-docker ]
      trigger: true
    - get: documentation-repo
      trigger: true
    - get: github-pages
  - task: update-docs
    config:
      platform: linux
      image: "docker:///guidowb/mkdocs-pipeline"
      inputs:
      - name: documentation-repo
      - name: github-pages
      outputs:
      - name: generated-repo
      run:
        path: sh
        args:
        - -exc
        - |
          (cd documentation-repo; mkdocs build --clean)
          cp -R github-pages/.git generated-repo
          cp -R documentation-repo/site/* generated-repo
          cd generated-repo
          git config user.name "CI Pipeline"
          git config user.email "ci-pipeline@localhost"
          git add --all
          git commit -m "Pipeline published updated docs"
  - put: github-pages
    params:
      repository: generated-repo
